CAMLP4=
OCAMLC_OPTS=-w '@f@p@u@s@40' -package
OCAMLOPT_OPTS=$(OCAMLC_OPTS)

TEST_MODULES=

EXTERNAL_DEPS=

.PHONY: all native-code byte-code test clean

all: native-code byte-code

# Dependencies
include ../lib/Ocamlrules.mk.in
