#!/usr/bin/env bash

set -e

function usage {
    exit 1
}

# n: required project name
# d: optional description
# r: optional remote
while getopts "n:r:d:" opt; do
    case "$opt" in
	n)
	    NAME=$OPTARG
	    ;;
	r)
	    REMOTE=$OPTARG
	    ;;
	d)
	    DESCRIPTION="$OPTARG"
	    ;;
	*)
	    usage
	    ;;
    esac
done

if [[ -z "$NAME" ]]; then
    usage
fi

shift $((OPTIND-1))

SCRIPT_DIR="$(dirname $0)"

"$SCRIPT_DIR/differentiate" $NAME $*
"$SCRIPT_DIR/enlighten" "$DESCRIPTION"
"$SCRIPT_DIR/advertise" $REMOTE
